### ISSUE TITLE
Error con la base de datos en heroku

### ISSUE THREAD

**Issue by DelPozoAmoAndres** [Arquisoft/radarin_es2b#101]
![image](https://user-images.githubusercontent.com/63802593/116799316-8d0d4300-aaf8-11eb-8be8-11e86d22a44b.png)
Cuando intentamos acceder a la base de datos vemos estos errores

**Comment by uo269736** [comment]
Problema solucionado, al final era un error que tenía fácil solución. Modificamos el server.js eliminando las opciones que no usabamos en el string mongo_uri y se arregló.
