### ISSUE TITLE
Actualizar la documentación

### ISSUE THREAD

**Issue by ialnavy** [Arquisoft/radarin_es2b#117]
Hay que terminar de actualizar la documentación, puesto que se encuentra en un estado que se corresponde con fases anteriores del proyecto y no con la actual.

**Comment by ialnavy** [comment]
- [Documentación. Bug en la tabla del apartado 12](https://github.com/Arquisoft/radarin_es2b/commit/07d82705ec8985c3ccf75dec0a74a55b96462641)
- [Documentación. Punto 1 actualizado](https://github.com/Arquisoft/radarin_es2b/commit/3c9036ea4bd9b66bfa1b807b7fdd23fa11451dd5)
- [Documentación. Punto 3 actualizado](https://github.com/Arquisoft/radarin_es2b/commit/7ec7770c5c639432e5d1fef4774dc2b58f43d2b6)
- [Documentación. Punto 4 actualizado](https://github.com/Arquisoft/radarin_es2b/commit/c74b5c41daa5436f4b0de8c2347f5ddd2e66892a)
- [Documentación. Punto 5 actualizado](https://github.com/Arquisoft/radarin_es2b/commit/868cbf18f7d9476dc603d7d837caa6382292308b)

Commits correspondientes a la siguiente pull request: [Documentación actualizada [1-5]](https://github.com/Arquisoft/radarin_es2b/pull/116)

**Comment by uo269736** [comment]
Actualizar los puntos 6, 7, 8, 9, 10, 11 y crear un nuevo apartado para las pruebas.

**Comment by uo269736** [comment]
Todo actualizado
