### ISSUE TITLE
Prototipos de interfaz de usuario de la aplicación

### ISSUE THREAD

**Issue by ialnavy** [Arquisoft/radarin_es2b#31]
Tal y como acordamos en el [acta de hoy](https://github.com/Arquisoft/radarin_es2b/wiki/%5B2021_03_01%5D-Acta), dejo aquí los primeros bocetos de mi propuesta de interfaz de usuario para la aplicación.
Queda pendiente acordar con cuál concepto nos quedaremos.

Nada más iniciar la aplicación, sin amigos cerca:

<img src="https://user-images.githubusercontent.com/56884738/109539661-dd006700-7ac1-11eb-8b96-c90f10d8dd28.jpg" height="480" width="270">

Nada más iniciar la aplicación, con 1 amigo cerca:

<img src="https://user-images.githubusercontent.com/56884738/109539671-dffb5780-7ac1-11eb-94c4-fb220fe5388c.jpg" height="480" width="270">

Habiendo pinchado en el marcador que identifica al amigo cercano:

<img src="https://user-images.githubusercontent.com/56884738/109539684-e25db180-7ac1-11eb-8ced-8d8864961f93.jpg" height="480" width="270">

Habiendo pinchado en el menú (arriba a la izquierda). Se cerraría volviéndole a dar:

<img src="https://user-images.githubusercontent.com/56884738/109539692-e4c00b80-7ac1-11eb-98e7-e52d3e4d9c8a.jpg" height="480" width="270">

**Comment by iyansl** [comment]
Añado mis propuestas para la interfaz de usuario de la aplicación.

Principal:
![Imagen1](https://user-images.githubusercontent.com/71704577/109549102-c7913a00-7acd-11eb-93e8-9a6fe0ef89ae.png)

Perfil (Botón izquierdo de la principal):
![imagen2 (2)](https://user-images.githubusercontent.com/71704577/109549141-da0b7380-7acd-11eb-9c51-347c185f9e60.png)

Amigos (Botón central de la principal):
![imagen3 (1)](https://user-images.githubusercontent.com/71704577/109549234-00311380-7ace-11eb-8faa-3936b7a1b7ac.png)

Configuración (Botón derecho de la principal):
![imagen4 (1)](https://user-images.githubusercontent.com/71704577/109549314-1c34b500-7ace-11eb-807b-e21549c28586.png)

**Comment by DelPozoAmoAndres** [comment]
Esta es mi propuesta:
Pantalla login
![iPhone XR, XS Max, 11 – 4](https://user-images.githubusercontent.com/63802593/109551823-52bfff00-7ad1-11eb-8dbf-5ce94c458f3a.png)
Pantalla principal
![iPhone XR, XS Max, 11 – 1](https://user-images.githubusercontent.com/63802593/109551814-50f63b80-7ad1-11eb-9028-d74b854eae1c.png)
Menu 
![iPhone XR, XS Max, 11 – 2](https://user-images.githubusercontent.com/63802593/109551819-52276880-7ad1-11eb-8c0e-4d2201b03261.png)
Amigos
![iPhone XR, XS Max, 11 – 3](https://user-images.githubusercontent.com/63802593/109551820-52276880-7ad1-11eb-9d8f-d03e6177c0c6.png)
Perfil
![iPhone XR, XS Max, 11 – 5](https://user-images.githubusercontent.com/63802593/109551826-52bfff00-7ad1-11eb-83d7-749a53d630eb.png)

**Comment by uo269736** [comment]
Esta es mi propuesta:
-
Inicio de sesión:
![pantallainiciarsesion](https://user-images.githubusercontent.com/71766104/109654193-2f916000-7b62-11eb-8cdb-3774bf1760f2.PNG)

-Pantalla principal:
![mapaInicial](https://user-images.githubusercontent.com/71766104/109654244-42a43000-7b62-11eb-9d48-536565099c93.PNG)

-Menu de opciones:
![menudeopciones](https://user-images.githubusercontent.com/71766104/109654387-6c5d5700-7b62-11eb-8dd5-5f99c474a018.PNG)

-Amigos:
![amigos](https://user-images.githubusercontent.com/71766104/109654399-71220b00-7b62-11eb-83f2-873813c4e898.PNG)

**Comment by UO269763** [comment]
Estos son mis prototipos de pantalla para la aplicación
PANTALLA DE INICIO DE SESIÓN
![PANTALLA DE INICIO DE SESIÓN](https://user-images.githubusercontent.com/71318681/109681892-362dd080-7b7e-11eb-80be-73822c10206b.jpeg)
PANTALLA PRINCIPAL QUE SE MUESTRA UNA VEZ INICIADA LA SESIÓN
![PANTALLA PRINCIPAL QUE SE MUESTRA UNA VEZ INICIADA LA SESIÓN](https://user-images.githubusercontent.com/71318681/109681932-3ded7500-7b7e-11eb-9925-6ca561c3d182.jpeg)
MENÚ LATERAL CON TODAS LAS OPCIONES DE LA APLICACIÓN
![MENÚ LATERAL CON TODAS LAS OPCIONES DE LA APLICACIÓN](https://user-images.githubusercontent.com/71318681/109682026-565d8f80-7b7e-11eb-849c-4df089a950d9.jpeg)
PANTALLA DEL PERFIL DEL PROPIO USUARIO
![PANTALLA DEL PERFIL DEL PROPIO USUARIO](https://user-images.githubusercontent.com/71318681/109682141-6bd2b980-7b7e-11eb-91da-8e76b6dc4ad8.jpeg)
PANTALLA PARA BUSCAR Y VER AMIGOS
![PANTALLA PARA BUSCAR Y VER AMIGOS](https://user-images.githubusercontent.com/71318681/109682214-7d1bc600-7b7e-11eb-9083-34a01e36ef05.jpeg)

**Comment by ialnavy** [comment]
Yo me quedaría con el diseño de Andrés, pero haría una combinación con lo que hay en mi diseño porque es fácil de hacer (de cara a una primera versión prototípica de la aplicación).
Los marcadores se hacen directamente (de hecho, en mi propuesta son capturas literales de OpenStreetMap), mientras que ponerles la foto de perfil de la gente a los marcadores dinámicamente veo más difícilmente cómo se podría hacer.
Si tuviese que elegir dos sin contar el mío, elegiría el de Andrés con las ventanas de _log-in_ y de editar el perfil de Esther, que las veo más completas.
Aún quedaría hablar de vistas como la del chat privado entre amigos, pero eso lo podríamos tratar en un futuro, al tratarse de una funcionabilidad secundaria de la aplicación.

**Comment by DelPozoAmoAndres** [comment]
![iPhone XR, XS Max, 11 – 15](https://user-images.githubusercontent.com/63802593/110330240-d754d500-801d-11eb-83a3-c4d22b512a3c.png)
![iPhone XR, XS Max, 11 – 13](https://user-images.githubusercontent.com/63802593/110330242-d7ed6b80-801d-11eb-9247-65bdef5e91f3.png)
![iPhone XR, XS Max, 11 – 14](https://user-images.githubusercontent.com/63802593/110330243-d8860200-801d-11eb-8a5d-21fa6a745e82.png)
![iPhone XR, XS Max, 11 – 12](https://user-images.githubusercontent.com/63802593/110330246-d8860200-801d-11eb-8a84-7c778195d248.png)
![iPhone XR, XS Max, 11 – 11](https://user-images.githubusercontent.com/63802593/110330247-d91e9880-801d-11eb-8b46-3c2e8c76841c.png)













Hemos decidido que este podría ser nuestro prototipo para la primera demo.
