### ISSUE TITLE
Despliegue en Heroku

### ISSUE THREAD

**Issue by ialnavy** [Arquisoft/radarin_es2b#63]
Vamos a desplegar nuestro proyecto en Heroku.

**Comment by ialnavy** [comment]
A la hora de desplegar el proyecto en Heroku, nos saltó un error relativo a que éste pesaba más de 1 GB, por lo tanto no se podía desplegar.
<img src="https://user-images.githubusercontent.com/56884738/114314329-7461cc80-9afa-11eb-8213-e24c27a8bab1.png">

**Comment by DelPozoAmoAndres** [comment]
Después de muchos intentos, vimos que el problema era node_modules. Se eliminó todo el contenido del mismo, nos dejó crear un build y parecía que todo iba bien. Hasta que intentamos lanzar la aplicación y nos saltó lo siguiente. No vimos manera de solucionarlo y decidimos hacer un rollback a la versión anterior donde era funcional.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/63802593/114324408-11882980-9b2a-11eb-8776-75720e5afc54.png)

**Comment by UO269763** [comment]
Finalmente, hemos conseguido hacer el despliegue en Heroku, solo de webapp. La aplicación está funcionando ahora en la url https://radarines2bwebapp.herokuapp.com/
