### ISSUE TITLE
Fallo con los botones en la vista móvil

### ISSUE THREAD

**Issue by uo269736** [Arquisoft/radarin_es2b#76]
Cuando abrimos la web lanzada en heroku desde el móvil no nos deja pulsar los botones de React.

**Comment by DelPozoAmoAndres** [comment]
Se ha corregido este fallo al cambiar las librerías de inicio de sesion y ahora desde móvil se puede navegar perfectamente
https://github.com/Arquisoft/radarin_es2b/commit/c5255cca8ee354ae33aff6becabeeccebb5be671
