### ISSUE TITLE
Creación de aplicación móvil

### ISSUE THREAD

**Issue by DelPozoAmoAndres** [Arquisoft/radarin_es2b#78]
se ha intentado hacer una aplicación que mediante un webview podamos ver el contenido de la pagina web, pero esta no carga el contenido de la pagina y se ve todo blanco. Se ha usado Android Studio

**Comment by UO269763** [comment]
El problema de la página en blanco pasa sólo en el emulador de Android Studio. Se ha mejorado la aplicación realizada en Android Studio, poniendo un icono y mejorando la vista.

**Comment by UO269763** [comment]
Ya se ha subido todo lo básico relacionado con la aplicación móvil #79
